name: Deploy to EKS

on: push

jobs:

  loginToAWS:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


  buildImage-and-Push-to-ECR:
    runs-on: ubuntu-latest
    needs:
      loginToAWS

    steps:

    - name: Code Checkout
      uses: actions/checkout@v4
      
    - name: Login to  AWS ECR
      uses: docker/login-action@v3
      with:
        registry: 765176032689.dkr.ecr.eu-west-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Image
      env:
         REGISTRY: 765176032689.dkr.ecr.eu-west-1.amazonaws.com
         REPO: merchant_api
         REPOSITORY_TAG: ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}

      run: |
        docker build -t ${REPO} .
        docker tag ${REPO}:latest ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}
        docker push ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}

  install_kubectl:
    runs-on: ubuntu-latest
    needs:
      buildImage-and-Push-to-ECR

    steps:

    - name: Install kubectl
      run: | 
         curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/OS_DISTRIBUTION/amd64/kubectl
         chmod +x ./kubectl
         sudo mv ./kubectl /usr/local/bin/kubectl
